### ISSUE TITLE
It's not clear in the docs that --seed 5 runs 1, 2, 3, and 4 but not 5.

### ISSUE THREAD

**Issue by issackelly** [paltman-archive/nashvegas#10]
I'm not sure if that is intentional or an off by one error.

**Comment by paltman** [comment]
make --seed behave as one would expect (closed by 3755ab06029860527935593cb4d6f39787c7a1f5)

**Comment by paltman** [comment]
fixed in 3755ab06029860527935593cb4d6f39787c7a1f5
