### ISSUE TITLE
ignore hidden files in db directory

### ISSUE THREAD

**Issue by Gautier** [paltman-archive/nashvegas#15]
If there are hidden files in the db directory, nashvegas will fail expecting migration file names to start with a digit.

See my fork for a patch.

**Comment by paltman** [comment]
Thanks.  Patched applied:

https://github.com/paltman/nashvegas/commit/9fe10a3e52d471918ba515363b54636a68f6e6d6

It will be in the nashvegas 0.5.2 release going out shortly.
