### ISSUE TITLE
Missing rollback feature

### ISSUE THREAD

**Issue by marcinn** [paltman-archive/nashvegas#25]
There is no way to rollback database schema. Sometimes you want step back to fix change set.

**Comment by peterbe** [comment]
Then you should perhaps look to use South instead. Rollbacks are complex but you could always just create a new migration that does the actual rollback for you. E.g. `ALTER TABLE DROP new_column`

**Comment by paltman** [comment]
I agree with peterbe, if you need rollbacks you should consider South. We do not plan on supporting rollbacks in nashvegas.
