### ISSUE TITLE
Issue with versioning

### ISSUE THREAD

**Issue by dcramer** [paltman-archive/nashvegas#41]
It seems the version is being recorded as "0.8" in setup.py, when it should be at the very least, 0.8.0

**Comment by paltman** [comment]
According to PEP 386 (http://www.python.org/dev/peps/pep-0386/) 0.8 and 0.8.0 are equivalent

**Comment by dcramer** [comment]
Ah so its just trimming it? If so then we can close this.

Was only concerned since I pushed 0.8 to our local PyPi (as we needed the pending changes in the pull requests)
